services:
- type: web
  name: flask-financial-project
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: startCommand: gunicorn -w 4 -b :10000 app:app
  envVars:
  - key: FLASK_APP
    value: app.py
  - key: FLASK_ENV
    value: production
